=== isublsv/JavaWebDevelopment/webparsing/src/main/resources/data/Medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.epam.com/medicines"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="medicines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drug" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element name="group">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Analgesics"/>
                                        <xs:enumeration value="Antibiotics"/>
                                        <xs:enumeration value="Antiseptics"/>
                                        <xs:enumeration value="Hormones"/>
                                        <xs:enumeration value="Stimulants"/>
                                        <xs:enumeration value="Vitamins"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="analogs" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="analog" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="versions">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tablets" type="Tablets" minOccurs="0"/>
                                        <xs:element name="drops" type="Drops" minOccurs="0"/>
                                        <xs:element name="powder" type="Powder" minOccurs="0"/>
                                        <xs:element name="ointment" type="Ointment" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:pattern value="([\d]){3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Form">
        <xs:sequence>
            <xs:element name="pharmacy" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="certificate" type="Certificate"/>
                        <xs:element name="package" type="TabletPackage"/>
                        <xs:element name="dosage" type="xs:decimal"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Certificate">
        <xs:sequence>
            <xs:element type="xs:positiveInteger" name="number"/>
            <xs:element type="xs:date" name="issue_date"/>
            <xs:element type="xs:date" name="expiration_date"/>
            <xs:element type="xs:string" name="registration"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TabletPackage">
        <xs:sequence>
            <xs:element name="packageType" type="PackType"/>
            <xs:element name="quantity">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:enumeration value="20"/>
                        <xs:enumeration value="50"/>
                        <xs:enumeration value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:decimal" name="price"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="LiquidPackage">
        <xs:sequence>
            <xs:element name="packageType" type="VolumeType"/>
            <xs:element name="volume">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:enumeration value="20"/>
                        <xs:enumeration value="50"/>
                        <xs:enumeration value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:decimal" name="price"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PowderPackage">
        <xs:sequence>
            <xs:element name="packageType" type="PowderType"/>
            <xs:element name="weight">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:enumeration value="20"/>
                        <xs:enumeration value="50"/>
                        <xs:enumeration value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:decimal" name="price"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OintmentPackage">
        <xs:sequence>
            <xs:element name="packageType" type="OintmentType"/>
            <xs:element name="weight">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:enumeration value="150"/>
                        <xs:enumeration value="200"/>
                        <xs:enumeration value="250"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:positiveInteger" name="concentration"/>
            <xs:element type="xs:decimal" name="price"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="PackType">
        <xs:simpleContent>
            <xs:restriction base="xs:string">                
                <xs:enumeration value="Plastic bottle"/>
                <xs:enumeration value="Blister pack"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="VolumeType">
        <xs:simpleContent>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Drop counter"/>
                <xs:enumeration value="Ampule"/>
                <xs:enumeration value="Glass bottle"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="PowderType">
        <xs:simpleContent>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Plastic bottle"/>
                <xs:enumeration value="Aluminum bag"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="OintmentType">
        <xs:simpleContent>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Tube"/>
                <xs:enumeration value="Ointment package"/>
            </xs:restriction>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="Tablets">
        <xs:complexContent>
            <xs:extension base="Form">
                <xs:sequence>
                    <xs:element name="pharmacy" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="certificate" type="Certificate"/>
                                <xs:element name="package" type="TabletPackage"/>
                                <xs:element name="dosage" type="xs:decimal"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Drops">
        <xs:complexContent>
            <xs:extension base="Form">
                <xs:sequence>
                    <xs:element name="pharmacy" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="certificate" type="Certificate"/>
                                <xs:element name="package" type="LiquidPackage"/>
                                <xs:element name="dosage" type="xs:decimal"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Powder">
        <xs:complexContent>
            <xs:extension base="Form">
                <xs:sequence>
                    <xs:element name="pharmacy" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="certificate" type="Certificate"/>
                                <xs:element name="package" type="PowderPackage"/>
                                <xs:element name="dosage" type="xs:decimal"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Ointment">
        <xs:complexContent>
            <xs:extension base="Form">
                <xs:sequence>
                    <xs:element name="pharmacy" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="certificate" type="Certificate"/>
                                <xs:element name="package" type="OintmentPackage"/>
                                <xs:element name="dosage" type="xs:decimal"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="form" type="Form" abstract="true"/>
    <xs:element name="tablets" type="Tablets" substitutionGroup="form"/>
    <xs:element name="drops" type="Drops" substitutionGroup="form"/>
    <xs:element name="powder" type="Powder" substitutionGroup="form"/>
    <xs:element name="ointment" type="Ointment" substitutionGroup="form"/>
</xs:schema>

=== isublsv/JavaWebDevelopment/webparsing/src/main/resources/data/Medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.epam.com/medicines"
           xsi:schemaLocation="http://www.epam.com/medicines Medicines.xsd">
    <!--
        Лекарственные препараты.
        Лекарственные препараты имеют следующие характеристики.
        1. Name – наименование препарата.
        2. Pharmacy – фирма-производитель.
        3. Group – группа препаратов к которым относится лекарство (антибиотики, болеутоляющие, витамины и т.п.).
        4. Analogs (может быть несколько) – содержит наименование аналога.
        5. Versions – варианты исполнения (консистенция/вид: таблетки, капсулы, порошок, капли и т.п.).
        Для каждого варианта исполнения может быть несколько производителей лекарственных препаратов
        со следующими характеристиками:
            5.1. Certificate – свидетельство о регистрации препарата (номер, даты выдачи/истечения действия,
            регистрирующая организация);
            5.2. Package – упаковка (тип упаковки, количество в упаковке, цена за упаковку);
            5.3. Dosage – дозировка препарата, периодичность приема.
        Корневой элемент назвать Medicines.
    -->
    <drug id="001">
        <name>Iodomarin</name>
        <group>Hormones</group>
        <analogs>
            <analog>Potassium iodide</analog>
        </analogs>
        <versions>
            <tablets>
                <pharmacy>
                    <certificate>
                        <number>123456789</number>
                        <issue_date>2017-10-12</issue_date>
                        <expiration_date>2021-10-12</expiration_date>
                        <registration>Berlin-Chemie AG, Germany</registration>
                    </certificate>                   
                    <package>
                        <packageType>Plastic bottle</packageType>
                        <quantity>75</quantity>
                        <price>18.99</price>
                    </package>
                    <dosage>0.1</dosage>
                </pharmacy>
                <pharmacy>
                    <certificate>
                        <number>123456789</number>
                        <issue_date>2017-10-12</issue_date>
                        <expiration_date>2021-10-12</expiration_date>
                        <registration>Berlin-Chemie AG, Germany</registration>
                    </certificate>
                    <package>
                        <packageType>Blister pack</packageType>
                        <quantity>50</quantity>
                        <price>12.99</price>
                    </package>                    
                    <dosage>0.2</dosage>
                </pharmacy>
            </tablets>
            <drops>
                <pharmacy>
                    <certificate>
                        <number>111222333</number>
                        <issue_date>2018-08-13</issue_date>
                        <expiration_date>2018-08-13</expiration_date>
                        <registration>Pharmacy Production, Belarus</registration>
                    </certificate>
                    <package>
                        <packageType>Drop counter</packageType>
                        <volume>50</volume>
                        <price>20</price>
                    </package>                    
                    <dosage>1</dosage>
                </pharmacy>
            </drops>
        </versions>
    </drug>
    <drug id="002">
        <name></name>
        <group>Vitamins</group>
        <versions>
            <tablets>
                <pharmacy>
                    <certificate>
                        <number></number>
                        <issue_date></issue_date>
                        <expiration_date></expiration_date>
                        <registration></registration>
                    </certificate>
                    <dosage></dosage>
                    <package>
                        <packageType></packageType>
                        <quantity></quantity>
                        <price></price>
                    </package>
                </pharmacy>
            </tablets>
        </versions>
    </drug>
    <drug id="003">
        <name></name>
        <group>Antibiotics</group>
        <versions></versions>
    </drug>
    <drug id="004">
        <name></name>
        <group>Analgesics</group>
        <versions></versions>
    </drug>
    <drug id="005">
        <name></name>
        <group>Antiseptics</group>
        <versions></versions>
    </drug>
    <drug id="006">
        <name></name>
        <group>Hormones</group>
        <versions></versions>
    </drug>
    <drug id="007">
        <name></name>
        <group>Stimulants</group>
        <versions></versions>
    </drug>
    <drug id="008">
        <name></name>
        <group>Vitamins</group>
        <versions></versions>
    </drug>
    <drug id="009">
        <name></name>
        <group>Antibiotics</group>
        <versions></versions>
    </drug>
    <drug id="010">
        <name></name>
        <group>Hormones</group>
        <versions></versions>
    </drug>
    <drug id="011">
        <name></name>
        <group>Vitamins</group>
        <versions></versions>
    </drug>
    <drug id="012">
        <name></name>
        <group>Analgesics</group>
        <versions></versions>
    </drug>
    <drug id="013">
        <name></name>
        <group>Antibiotics</group>
        <versions></versions>
    </drug>
    <drug id="014">
        <name></name>
        <group>Stimulants</group>
        <versions></versions>
    </drug>
    <drug id="015">
        <name></name>
        <group>Hormones</group>
        <versions></versions>
    </drug>
    <drug id="016">
        <name></name>
        <group>Antiseptics</group>
        <versions></versions>
    </drug>
</medicines>
